export const quotes = [
  "Life is what happens when you're busy making other plans.",
  "He who dares nothing, need hope for nothing.",
  "The only way to do great work is to love what you do.",
  "Happiness is not something ready made. It comes from your own actions.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Do not count the days, make the days count.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "It's not what happens to us, but our response to what happens to us that hurts us.",
  "Life is 10% what happens to me and 90% of how I react to it.",
  "There is only one thing that makes a dream impossible to achieve: the fear of failure.",
  "Choose a job you love, and you will never have to work a day in your life.",
  "Life is really simple, but we insist on making it complicated.",
  "Happiness is not the absence of problems; it's the ability to deal with them.",
  "Be yourself; everyone else is already taken.",
  "What we do in life echoes in eternity.",
  "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "Life is a journey that must be traveled no matter how bad the roads and accommodations.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Act as if what you do makes a difference. It does.",
  "Success usually comes to those who are too busy to be looking for it.",
  "The best way to predict the future is to invent it.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "Do what you can, with what you have, where you are.",
  "You miss 100% of the shots you don't take.",
  "Whether you think you can or you think you can't, you're right.",
  "The secret of getting ahead is getting started.",
  "It's not the years in your life that count. It's the life in your years.",
  "Either you run the day, or the day runs you.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams! Live the life you've imagined.",
  "Life shrinks or expands in proportion to one's courage.",
  "The mind is everything. What you think you become.",
  "The best revenge is massive success.",
  "An unexamined life is not worth living.",
  "Eighty percent of success is showing up.",
  "Your time is limited, don’t waste it living someone else’s life.",
  "Winning isn’t everything, but wanting to win is.",
];
